title                   : "Yuma Matsuoka"  
description             : "I'm a graduate student in Hosei Univeristy and Johns Hopkins Univeristy. I'm studying machine learning, computer vision especially deep learning and the derivation."
google_analytics        : "UA-112843722-1"
theme                   : "jekyll-theme-minimal"
